package co.edu.usbcali.modelo;
// Generated 14/05/2017 01:16:03 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fotografia generated by hbm2java
 */
public class Fotografia implements java.io.Serializable {

	private long fotoId;
	private byte[] imagenbin;
	private String usuCreador;
	private String usuModificador;
	private Date fechaCreador;
	private Date fechaModificador;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Fotografia() {
	}

	public Fotografia(long fotoId, String usuCreador, Date fechaCreador) {
		this.fotoId = fotoId;
		this.usuCreador = usuCreador;
		this.fechaCreador = fechaCreador;
	}

	public Fotografia(long fotoId, byte[] imagenbin, String usuCreador, String usuModificador, Date fechaCreador,
			Date fechaModificador, Set<Usuario> usuarios) {
		this.fotoId = fotoId;
		this.imagenbin = imagenbin;
		this.usuCreador = usuCreador;
		this.usuModificador = usuModificador;
		this.fechaCreador = fechaCreador;
		this.fechaModificador = fechaModificador;
		this.usuarios = usuarios;
	}

	public long getFotoId() {
		return this.fotoId;
	}

	public void setFotoId(long fotoId) {
		this.fotoId = fotoId;
	}

	public byte[] getImagenbin() {
		return this.imagenbin;
	}

	public void setImagenbin(byte[] imagenbin) {
		this.imagenbin = imagenbin;
	}

	public String getUsuCreador() {
		return this.usuCreador;
	}

	public void setUsuCreador(String usuCreador) {
		this.usuCreador = usuCreador;
	}

	public String getUsuModificador() {
		return this.usuModificador;
	}

	public void setUsuModificador(String usuModificador) {
		this.usuModificador = usuModificador;
	}

	public Date getFechaCreador() {
		return this.fechaCreador;
	}

	public void setFechaCreador(Date fechaCreador) {
		this.fechaCreador = fechaCreador;
	}

	public Date getFechaModificador() {
		return this.fechaModificador;
	}

	public void setFechaModificador(Date fechaModificador) {
		this.fechaModificador = fechaModificador;
	}

	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
