package co.edu.usbcali.modelo;
// Generated 14/05/2017 01:16:03 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ingreso generated by hbm2java
 */
public class Ingreso implements java.io.Serializable {

	private long ingrId;
	private Date fechaingreso;
	private Date horaingreso;
	private String usuCreador;
	private String usuModificador;
	private Date fechaCreador;
	private Date fechaModificador;
	private Set<InoutDaily> inoutDailies = new HashSet<InoutDaily>(0);

	public Ingreso() {
	}

	public Ingreso(long ingrId, String usuCreador, Date fechaCreador) {
		this.ingrId = ingrId;
		this.usuCreador = usuCreador;
		this.fechaCreador = fechaCreador;
	}

	public Ingreso(long ingrId, Date fechaingreso, Date horaingreso, String usuCreador, String usuModificador,
			Date fechaCreador, Date fechaModificador, Set<InoutDaily> inoutDailies) {
		this.ingrId = ingrId;
		this.fechaingreso = fechaingreso;
		this.horaingreso = horaingreso;
		this.usuCreador = usuCreador;
		this.usuModificador = usuModificador;
		this.fechaCreador = fechaCreador;
		this.fechaModificador = fechaModificador;
		this.inoutDailies = inoutDailies;
	}

	public long getIngrId() {
		return this.ingrId;
	}

	public void setIngrId(long ingrId) {
		this.ingrId = ingrId;
	}

	public Date getFechaingreso() {
		return this.fechaingreso;
	}

	public void setFechaingreso(Date fechaingreso) {
		this.fechaingreso = fechaingreso;
	}

	public Date getHoraingreso() {
		return this.horaingreso;
	}

	public void setHoraingreso(Date horaingreso) {
		this.horaingreso = horaingreso;
	}

	public String getUsuCreador() {
		return this.usuCreador;
	}

	public void setUsuCreador(String usuCreador) {
		this.usuCreador = usuCreador;
	}

	public String getUsuModificador() {
		return this.usuModificador;
	}

	public void setUsuModificador(String usuModificador) {
		this.usuModificador = usuModificador;
	}

	public Date getFechaCreador() {
		return this.fechaCreador;
	}

	public void setFechaCreador(Date fechaCreador) {
		this.fechaCreador = fechaCreador;
	}

	public Date getFechaModificador() {
		return this.fechaModificador;
	}

	public void setFechaModificador(Date fechaModificador) {
		this.fechaModificador = fechaModificador;
	}

	public Set<InoutDaily> getInoutDailies() {
		return this.inoutDailies;
	}

	public void setInoutDailies(Set<InoutDaily> inoutDailies) {
		this.inoutDailies = inoutDailies;
	}

}
