package co.edu.usbcali.modelo;
// Generated 14/05/2017 01:16:03 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * InoutDaily generated by hbm2java
 */
public class InoutDaily implements java.io.Serializable {

	private long indaId;
	private Bitacora bitacora;
	private Ingreso ingreso;
	private Salida salida;
	private String observacion;
	private String usuCreador;
	private String usuModificador;
	private Date fechaCreador;
	private Date fechaModificador;

	public InoutDaily() {
	}

	public InoutDaily(long indaId, String usuCreador, Date fechaCreador) {
		this.indaId = indaId;
		this.usuCreador = usuCreador;
		this.fechaCreador = fechaCreador;
	}

	public InoutDaily(long indaId, Bitacora bitacora, Ingreso ingreso, Salida salida, String observacion,
			String usuCreador, String usuModificador, Date fechaCreador, Date fechaModificador) {
		this.indaId = indaId;
		this.bitacora = bitacora;
		this.ingreso = ingreso;
		this.salida = salida;
		this.observacion = observacion;
		this.usuCreador = usuCreador;
		this.usuModificador = usuModificador;
		this.fechaCreador = fechaCreador;
		this.fechaModificador = fechaModificador;
	}

	public long getIndaId() {
		return this.indaId;
	}

	public void setIndaId(long indaId) {
		this.indaId = indaId;
	}

	public Bitacora getBitacora() {
		return this.bitacora;
	}

	public void setBitacora(Bitacora bitacora) {
		this.bitacora = bitacora;
	}

	public Ingreso getIngreso() {
		return this.ingreso;
	}

	public void setIngreso(Ingreso ingreso) {
		this.ingreso = ingreso;
	}

	public Salida getSalida() {
		return this.salida;
	}

	public void setSalida(Salida salida) {
		this.salida = salida;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public String getUsuCreador() {
		return this.usuCreador;
	}

	public void setUsuCreador(String usuCreador) {
		this.usuCreador = usuCreador;
	}

	public String getUsuModificador() {
		return this.usuModificador;
	}

	public void setUsuModificador(String usuModificador) {
		this.usuModificador = usuModificador;
	}

	public Date getFechaCreador() {
		return this.fechaCreador;
	}

	public void setFechaCreador(Date fechaCreador) {
		this.fechaCreador = fechaCreador;
	}

	public Date getFechaModificador() {
		return this.fechaModificador;
	}

	public void setFechaModificador(Date fechaModificador) {
		this.fechaModificador = fechaModificador;
	}

}
