package co.edu.usbcali.modelo;
// Generated 14/05/2017 01:16:03 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * Parametro generated by hbm2java
 */
public class Parametro implements java.io.Serializable {

	private int paraId;
	private String valor;
	private String descripcion;
	private String usuCreador;
	private String usuModificador;
	private Date fechaCreador;
	private Date fechaModificador;

	public Parametro() {
	}

	public Parametro(int paraId, String valor, String descripcion, String usuCreador, Date fechaCreador) {
		this.paraId = paraId;
		this.valor = valor;
		this.descripcion = descripcion;
		this.usuCreador = usuCreador;
		this.fechaCreador = fechaCreador;
	}

	public Parametro(int paraId, String valor, String descripcion, String usuCreador, String usuModificador,
			Date fechaCreador, Date fechaModificador) {
		this.paraId = paraId;
		this.valor = valor;
		this.descripcion = descripcion;
		this.usuCreador = usuCreador;
		this.usuModificador = usuModificador;
		this.fechaCreador = fechaCreador;
		this.fechaModificador = fechaModificador;
	}

	public int getParaId() {
		return this.paraId;
	}

	public void setParaId(int paraId) {
		this.paraId = paraId;
	}

	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getUsuCreador() {
		return this.usuCreador;
	}

	public void setUsuCreador(String usuCreador) {
		this.usuCreador = usuCreador;
	}

	public String getUsuModificador() {
		return this.usuModificador;
	}

	public void setUsuModificador(String usuModificador) {
		this.usuModificador = usuModificador;
	}

	public Date getFechaCreador() {
		return this.fechaCreador;
	}

	public void setFechaCreador(Date fechaCreador) {
		this.fechaCreador = fechaCreador;
	}

	public Date getFechaModificador() {
		return this.fechaModificador;
	}

	public void setFechaModificador(Date fechaModificador) {
		this.fechaModificador = fechaModificador;
	}

}
